(cl:in-package xiaoyi_swd-msg)
(cl:export '(BDTA_USE-VAL
          BDTA_USE
          BDTA0-VAL
          BDTA0
          BDTA1-VAL
          BDTA1
          BDTA2-VAL
          BDTA2
          IDTA_USE-VAL
          IDTA_USE
          IDTA0-VAL
          IDTA0
          IDTA1-VAL
          IDTA1
          IDTA2-VAL
          IDTA2
          FDTA_USE-VAL
          FDTA_USE
          FDTA0-VAL
          FDTA0
          FDTA1-VAL
          FDTA1
          FDTA2-VAL
          FDTA2
          CARRAY_USE-VAL
          CARRAY_USE
          CARRAY0-VAL
          CARRAY0
          CARRAY1-VAL
          CARRAY1
          CARRAY2-VAL
          CARRAY2
          IARRAY_USE-VAL
          IARRAY_USE
          IARRAY0-VAL
          IARRAY0
          IARRAY1-VAL
          IARRAY1
          FARRAY_USE-VAL
          FARRAY_USE
          FARRAY0-VAL
          FARRAY0
          FARRAY1-VAL
          FARRAY1
          FARRAY2-VAL
          FARRAY2
          FARRAY3-VAL
          FARRAY3
          FARRAY4-VAL
          FARRAY4
          FARRAY5-VAL
          FARRAY5
          POINT32DTA-VAL
          POINT32DTA
          POSEDTA-VAL
          POSEDTA
))