set(_CATKIN_CURRENT_PACKAGE "xiaoyi_bot")
set(xiaoyi_bot_MAINTAINER "cyb7369299 <cyb7369299@todo.todo>")
set(xiaoyi_bot_DEPRECATED "")
set(xiaoyi_bot_VERSION "0.0.0")
set(xiaoyi_bot_BUILD_DEPENDS "geometry_msgs" "roscpp" "rospy" "std_msgs")
set(xiaoyi_bot_RUN_DEPENDS "geometry_msgs" "roscpp" "rospy" "std_msgs")
set(xiaoyi_bot_BUILDTOOL_DEPENDS "catkin" "genmsg")