set(_CATKIN_CURRENT_PACKAGE "yb_botguider")
set(yb_botguider_MAINTAINER "cyb7369299 <cyb7369299@todo.todo>")
set(yb_botguider_DEPRECATED "")
set(yb_botguider_VERSION "0.0.0")
set(yb_botguider_BUILD_DEPENDS "roscpp" "rospy" "std_msgs" "tf")
set(yb_botguider_RUN_DEPENDS "roscpp" "rospy" "std_msgs" "tf")
set(yb_botguider_BUILDTOOL_DEPENDS "catkin")